# Cluster & tier assignments

Runs `src.clustering.assign_tiers` on the forecast + PWC data to produce per-MSOA cluster labels and tiers for a chosen month.

**Inputs**
 `data/raw/centroids/msoa_2021_PWCs.csv` population-weighted centroids.
 `data/processed/wide_forecasts.csv` the `wide_forecasts` table built in `regression test.ipynb`.
  It carries `msoa_code`, `month`, and `intensity` columns, which is what `assign_tiers` needs.

Run Jupyter from the repo root so `import src` resolves.

In [45]:
import os
from pathlib import Path

# from dev manual: be at root so 'from src...' resolves.
if not Path("src").is_dir():
    os.chdir(Path.cwd().parent)

import pandas as pd

from src.config import DATA_DIR, RAW_DIR
from src.clustering import assign_tiers, load_pwc_coords

## 1. PWC coordinates
Raw columns `X, Y, MSOA21CD` renamed to `easting, northing, msoa_code`.

In [46]:
pwc = load_pwc_coords(pd.read_csv(RAW_DIR / "centroids" / "msoa_2021_PWCs.csv"))
pwc.head()

   msoa_code      easting     northing
0  E02000001  532290.3638  181745.9359
1  E02004372  582475.5406  110963.8205
2  E02006584  524353.1856  135416.2588
3  E02006411  504326.1721  170345.3420
4  E02003401  470327.0410  172513.7070

Prerequisite

In [47]:
# PREREQUISITE 
# do NOT run this cell here. It is commented out on purpose.                                    
                                                                                                      
# The next section reads data/processed/wide_forecasts.csv. That file is NOT                                
# in git (data/processed/ is gitignored), so it must be generated once from                                  
# the regression notebook before this notebook can run.                                             
                                                                                                            
# HOW TO GENERATE IT:                                                                                          
#   1. Open regression test.ipynb and run it top to bottom so the                                            
#      wide_forecasts DataFrame exists in that kernel's memory.                                              
#   2. With wide_forecasts still in memory, add a new cell at the bottom of                                  
#      regression test.ipynb containing exactly the code below, and run it.                                  
#   3. It writes the CSV to data/processed/. After that, this notebook can read                                
#      it and you do not need to rerun regression again unless forecasts change. 
#   4. after wide_forecasts.csv is saved, delete the code to avoid bloating the other notebook with non regression related code
                                                                                                             
#  Paste the following into regression test.ipynb, NOT into this notebook:                            
#                                                                                                              
# from src.config import DATA_DIR                                                                              
# DATA_DIR.mkdir(parents=True, exist_ok=True)                                                                  
# wide_forecasts.to_csv(DATA_DIR / "wide_forecasts.csv", index=False)

## 2. Forecasts
`wide_forecasts` already contains `msoa_code`, `month`, `intensity`. `assign_tiers` slices the columns it needs

In [48]:
wide_forecasts = pd.read_csv(
    DATA_DIR / "wide_forecasts.csv", parse_dates=["month"]
)
wide_forecasts[["msoa_code", "month", "intensity"]].head()

   msoa_code      month     intensity
0  E02000001 2026-04-01  95897.337353
1  E02000001 2026-05-01  96968.920126
2  E02000001 2026-06-01  97840.604673
3  E02000001 2026-07-01  97630.016938
4  E02000001 2026-08-01  97634.355015

## 3. Pick a month
`assign_tiers` clusters one month at a time. Output available months:

In [49]:
months = sorted(wide_forecasts["month"].dt.strftime("%Y-%m-%d").unique())

In [50]:
months_threshold = {}
for MONTH in months:
    # Intensity cutoff for at-risk (TIER 2) noise points, taken from the specific month's distribution.
    month_intensity = wide_forecasts.loc[wide_forecasts["month"] == MONTH, "intensity"]
    threshold_value = 0.9
    THRESHOLD = month_intensity.quantile(threshold_value)
    months_threshold[MONTH] = THRESHOLD
    print(f"Threshold ({threshold_value}th pct of intensity for {MONTH}): {THRESHOLD:.3f}")

Threshold (0.9th pct of intensity for 2026-04-01): 15556.572
Threshold (0.9th pct of intensity for 2026-05-01): 15429.267
Threshold (0.9th pct of intensity for 2026-06-01): 15427.321
Threshold (0.9th pct of intensity for 2026-07-01): 15558.886
Threshold (0.9th pct of intensity for 2026-08-01): 15503.781
Threshold (0.9th pct of intensity for 2026-09-01): 15140.043
Threshold (0.9th pct of intensity for 2026-10-01): 15306.918
Threshold (0.9th pct of intensity for 2026-11-01): 15006.021
Threshold (0.9th pct of intensity for 2026-12-01): 14861.610
Threshold (0.9th pct of intensity for 2027-01-01): 14657.173
Threshold (0.9th pct of intensity for 2027-02-01): 14241.581
Threshold (0.9th pct of intensity for 2027-03-01): 14507.624

## 4. Cluster & assign tiers

In [ ]:
results = {}
for MONTH in months_threshold:
    result = assign_tiers(
    wide_forecasts,
    pwc,
    month=MONTH,
    threshold=months_threshold[MONTH],
    intensity_cap_quantile=0.95,
    min_cluster_size=5,
    )
    results[MONTH] = result

   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  95897.337353            224
1  E02000002  547988.0185  189412.9491   9689.155164             -1
2  E02000003  548362.0317  188088.2498  15795.621326             -1
3  E02000004  551020.1697  186865.3459   5584.097231             -1
4  E02000005  548629.9425  186875.2643   9930.507955             -1

   membership_prob    tier  final_weight
0              1.0  Tier 1  95897.337353
1              0.0  Tier 3    484.457758
2              0.0  Tier 2   7897.810663
3              0.0  Tier 3    279.204862
4              0.0  Tier 3    496.525398

## 5. Print results

In [56]:
for MONTH in results:
    print(results[MONTH].head())

   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  95897.337353            224
1  E02000002  547988.0185  189412.9491   9689.155164             -1
2  E02000003  548362.0317  188088.2498  15795.621326             -1
3  E02000004  551020.1697  186865.3459   5584.097231             -1
4  E02000005  548629.9425  186875.2643   9930.507955             -1

   membership_prob    tier  final_weight
0              1.0  Tier 1  95897.337353
1              0.0  Tier 3    484.457758
2              0.0  Tier 2   7897.810663
3              0.0  Tier 3    279.204862
4              0.0  Tier 3    496.525398
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  96968.920126            231
1  E02000002  547988.0185  189412.9491   9348.095680            254
2  E02000003  548362.0317  188088.2498  14598.665053             -1
3  E02000004  551020.1697  186865.3459   5760.995042            254
4  E02000005  548629.9425  186875.2643  10132.843818            254

   membership_prob    tier  final_weight
0         1.000000  Tier 1  96968.920126
1         0.938164  Tier 1   9348.095680
2         0.000000  Tier 3    729.933253
3         0.984774  Tier 1   5760.995042
4         1.000000  Tier 1  10132.843818
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  97840.604673            246
1  E02000002  547988.0185  189412.9491   9842.813975             -1
2  E02000003  548362.0317  188088.2498  13743.250896            283
3  E02000004  551020.1697  186865.3459   5847.581334             -1
4  E02000005  548629.9425  186875.2643  11372.715331             -1

   membership_prob    tier  final_weight
0         0.980451  Tier 1  97840.604673
1         0.000000  Tier 3    492.140699
2         1.000000  Tier 1  13743.250896
3         0.000000  Tier 3    292.379067
4         0.000000  Tier 3    568.635767
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  97630.016938            168
1  E02000002  547988.0185  189412.9491  10106.577837            257
2  E02000003  548362.0317  188088.2498  14473.911491             -1
3  E02000004  551020.1697  186865.3459   5656.257704            257
4  E02000005  548629.9425  186875.2643  11140.814623            257

   membership_prob    tier  final_weight
0         0.980451  Tier 1  97630.016938
1         1.000000  Tier 1  10106.577837
2         0.000000  Tier 3    723.695575
3         0.882371  Tier 1   5656.257704
4         0.881299  Tier 1  11140.814623
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  97634.355015            215
1  E02000002  547988.0185  189412.9491  10824.772264             -1
2  E02000003  548362.0317  188088.2498  13732.580765             -1
3  E02000004  551020.1697  186865.3459   5742.128964             -1
4  E02000005  548629.9425  186875.2643  10587.499519             -1

   membership_prob    tier  final_weight
0              1.0  Tier 1  97634.355015
1              0.0  Tier 3    541.238613
2              0.0  Tier 3    686.629038
3              0.0  Tier 3    287.106448
4              0.0  Tier 3    529.374976
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  95307.082083            180
1  E02000002  547988.0185  189412.9491  11012.106526             -1
2  E02000003  548362.0317  188088.2498  12651.167913             -1
3  E02000004  551020.1697  186865.3459   5771.154645            253
4  E02000005  548629.9425  186875.2643  11629.059481             -1

   membership_prob    tier  final_weight
0         1.000000  Tier 1  95307.082083
1         0.000000  Tier 3    550.605326
2         0.000000  Tier 3    632.558396
3         0.891016  Tier 1   5771.154645
4         0.000000  Tier 3    581.452974
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  96985.259001            163
1  E02000002  547988.0185  189412.9491   9726.658892             -1
2  E02000003  548362.0317  188088.2498  13523.324036             -1
3  E02000004  551020.1697  186865.3459   5918.231835            257
4  E02000005  548629.9425  186875.2643  12660.494866            257

   membership_prob    tier  final_weight
0              1.0  Tier 1  96985.259001
1              0.0  Tier 3    486.332945
2              0.0  Tier 3    676.166202
3              1.0  Tier 1   5918.231835
4              1.0  Tier 1  12660.494866
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  95060.651278            229
1  E02000002  547988.0185  189412.9491  11176.588233             -1
2  E02000003  548362.0317  188088.2498  15494.418382             -1
3  E02000004  551020.1697  186865.3459   6098.160444            261
4  E02000005  548629.9425  186875.2643  11938.261061             -1

   membership_prob    tier  final_weight
0              1.0  Tier 1  95060.651278
1              0.0  Tier 3    558.829412
2              0.0  Tier 2   7747.209191
3              1.0  Tier 1   6098.160444
4              0.0  Tier 3    596.913053
   msoa_code      easting     northing      intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  101880.207326            223
1  E02000002  547988.0185  189412.9491   10595.698367             -1
2  E02000003  548362.0317  188088.2498   15361.488735             -1
3  E02000004  551020.1697  186865.3459    6001.158005             -1
4  E02000005  548629.9425  186875.2643   11972.188266            266

   membership_prob    tier   final_weight
0         1.000000  Tier 1  101880.207326
1         0.000000  Tier 3     529.784918
2         0.000000  Tier 2    7680.744368
3         0.000000  Tier 3     300.057900
4         0.956348  Tier 1   11972.188266
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  98932.626521            270
1  E02000002  547988.0185  189412.9491  10718.630920             -1
2  E02000003  548362.0317  188088.2498  15006.494300            272
3  E02000004  551020.1697  186865.3459   5890.073606            282
4  E02000005  548629.9425  186875.2643  12010.769628             -1

   membership_prob    tier  final_weight
0         1.000000  Tier 1  98932.626521
1         0.000000  Tier 3    535.931546
2         0.886830  Tier 1  15006.494300
3         0.951425  Tier 1   5890.073606
4         0.000000  Tier 3    600.538481
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  93797.360168            233
1  E02000002  547988.0185  189412.9491  10552.272587            246
2  E02000003  548362.0317  188088.2498  14369.867280            236
3  E02000004  551020.1697  186865.3459   6356.614041            246
4  E02000005  548629.9425  186875.2643  11308.200585             -1

   membership_prob    tier  final_weight
0         0.980451  Tier 1  93797.360168
1         1.000000  Tier 1  10552.272587
2         1.000000  Tier 1  14369.867280
3         1.000000  Tier 1   6356.614041
4         0.000000  Tier 3    565.410029
   msoa_code      easting     northing     intensity  cluster_label  \
0  E02000001  532290.3638  181745.9359  91936.945425            160
1  E02000002  547988.0185  189412.9491  10342.052349            264
2  E02000003  548362.0317  188088.2498  14367.161027             -1
3  E02000004  551020.1697  186865.3459   6360.380518             -1
4  E02000005  548629.9425  186875.2643  10665.067064            264

   membership_prob    tier  final_weight
0         1.000000  Tier 1  91936.945425
1         0.902178  Tier 1  10342.052349
2         0.000000  Tier 3    718.358051
3         0.000000  Tier 3    318.019026
4         0.901855  Tier 1  10665.067064

## 6. Save results in /data/processed

In [58]:
for MONTH in results:   
    (DATA_DIR / 'yearly_tiers').mkdir(parents=True, exist_ok=True)
    out_path = DATA_DIR / 'yearly_tiers' /f"tier_assignments_{MONTH}.csv"
    result.to_csv(out_path, index=False)
    print(out_path)

/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-04-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-05-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-06-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-07-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-08-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-09-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-10-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-11-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2026-12-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2027-01-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2027-02-01.csv
/home/rbilous/TUe-Multi-Disciplinary-CBL/data/processed/yearly_tiers/tier_assignments_2027-03-01.csv