# Cluster & tier assignments

Runs `src.clustering.assign_tiers` on the forecast + PWC data to produce per-MSOA cluster labels and tiers for a chosen month.

**Inputs**
 `data/raw/centroids/msoa_2021_PWCs.csv` population-weighted centroids.
 `data/processed/wide_forecasts.csv` the `wide_forecasts` table built in `regression test.ipynb`.
  It carries `msoa_code`, `month`, and `intensity` columns, which is what `assign_tiers` needs.

Run Jupyter from the repo root so `import src` resolves.

In [11]:
import os
from pathlib import Path

# from dev manual: be at root so 'from src...' resolves.
if not Path("src").is_dir():
    os.chdir(Path.cwd().parent)

import pandas as pd

from src.config import DATA_DIR, RAW_DIR
from src.clustering import assign_tiers, load_pwc_coords

## 1. PWC coordinates
Raw columns `X, Y, MSOA21CD` renamed to `easting, northing, msoa_code`.

In [12]:
pwc = load_pwc_coords(pd.read_csv(RAW_DIR / "centroids" / "msoa_2021_PWCs.csv"))
pwc.head()

   msoa_code      easting     northing
0  E02000001  532290.3638  181745.9359
1  E02004372  582475.5406  110963.8205
2  E02006584  524353.1856  135416.2588
3  E02006411  504326.1721  170345.3420
4  E02003401  470327.0410  172513.7070

Prerequisite

In [ ]:
# PREREQUISITE 
# do NOT run this cell here. It is commented out on purpose.                                    
                                                                                                      
# The next section reads data/processed/wide_forecasts.csv. That file is NOT                                
# in git (data/processed/ is gitignored), so it must be generated once from                                  
# the regression notebook before this notebook can run.                                             
                                                                                                            
# HOW TO GENERATE IT:                                                                                          
#   1. Open regression test.ipynb and run it top to bottom so the                                            
#      wide_forecasts DataFrame exists in that kernel's memory.                                              
#   2. With wide_forecasts still in memory, add a new cell at the bottom of                                  
#      regression test.ipynb containing exactly the code below, and run it.                                  
#   3. It writes the CSV to data/processed/. After that, this notebook can read                                
#      it and you do not need to rerun regression again unless forecasts change. 
#   4. after wide_forecasts.csv is saved, delete the code to avoid bloating the other notebook with non regression related code
                                                                                                             
#  Paste the following into regression test.ipynb, NOT into this notebook:                            
#                                                                                                              
# from src.config import DATA_DIR                                                                              
# DATA_DIR.mkdir(parents=True, exist_ok=True)                                                                  
# wide_forecasts.to_csv(DATA_DIR / "wide_forecasts.csv", index=False)

## 2. Forecasts
`wide_forecasts` already contains `msoa_code`, `month`, `intensity`. `assign_tiers` slices the columns it needs

In [15]:
from sqlalchemy import create_engine 
import pandas as pd
engine = create_engine("postgresql+psycopg2://data_admin:TUE123@localhost:5433/cbl_policing")
wide_forecasts = pd.read_sql("""SELECT *
                             FROM wideforecast
""",engine
    
)
wide_forecasts[["msoa_code", "month", "intensity"]].head()

   msoa_code      month     intensity
0  E02000001 2026-04-01  95897.337353
1  E02000001 2026-05-01  96968.920126
2  E02000001 2026-06-01  97840.604673
3  E02000001 2026-07-01  97630.016938
4  E02000001 2026-08-01  97634.355015

## 3. Pick a month
`assign_tiers` clusters one month at a time. Output available months:

In [16]:
sorted(wide_forecasts["month"].dt.strftime("%Y-%m-%d").unique())

['2026-04-01',
 '2026-05-01',
 '2026-06-01',
 '2026-07-01',
 '2026-08-01',
 '2026-09-01',
 '2026-10-01',
 '2026-11-01',
 '2026-12-01',
 '2027-01-01',
 '2027-02-01',
 '2027-03-01']

In [ ]:
MONTH = "2026-04-01"   #the value I tested on

# Intensity cutoff for at-risk (TIER 2) noise points, taken from the specific month's distribution.
month_intensity = wide_forecasts.loc[wide_forecasts["month"] == MONTH, "intensity"]
THRESHOLD = month_intensity.quantile(0.75)
print(f"Threshold (75th pct of intensity for {MONTH}): {THRESHOLD:.3f}")

Threshold (75th pct of intensity for 2026-04-01): 10404.210

## 4. Cluster & assign tiers

In [18]:
result = assign_tiers(
    wide_forecasts,
    pwc,
    month=MONTH,
    threshold=THRESHOLD,
    intensity_cap_quantile=0.95,
    min_cluster_size=5,
)
result.head()

,msoa_code,easting,northing,intensity,cluster_label,membership_prob,tier,final_weight
0,E02000001,532290.3638,181745.9359,95897.337353,228,1.0,Tier 1,95897.337353
1,E02000002,547988.0185,189412.9491,9689.155164,-1,0.0,Tier 3,484.457758
2,E02000003,548362.0317,188088.2498,15795.621326,-1,0.0,Tier 2,7897.810663
3,E02000004,551020.1697,186865.3459,5584.097231,-1,0.0,Tier 3,279.204862
4,E02000005,548629.9425,186875.2643,9930.507955,-1,0.0,Tier 3,496.525398

## 5. change tiers of t1 neighbours

In [27]:
import geopandas as gpd

boundaries = gpd.read_file("data/raw/boundaries/msoa_2021_Boundaries_BSC.gpkg")
boundaries = boundaries[["MSOA21CD","MSOA21NM","geometry"]]
boundaries = boundaries.rename(columns={

    "MSOA21CD": "msoa_code",

    "MSOA21NM": "msoa21nm"

})
boundaries.head()

,msoa_code,msoa21nm,geometry
0,E02000001,City of London 001,"MULTIPOLYGON (((532946.065 181894.827, 532135...."
1,E02000002,Barking and Dagenham 001,"MULTIPOLYGON (((549000.726 190873.464, 548877...."
2,E02000003,Barking and Dagenham 002,"MULTIPOLYGON (((548954.517 189063.241, 549120...."
3,E02000004,Barking and Dagenham 003,"MULTIPOLYGON (((551943.781 186027.614, 551391...."
4,E02000005,Barking and Dagenham 004,"MULTIPOLYGON (((549418.68 187442.412, 549099.6..."

In [54]:
tiersWboundaries = result.merge(boundaries,on= "msoa_code",how="left")
tiersWboundaries = gpd.GeoDataFrame(tiersWboundaries,geometry="geometry",crs=boundaries.crs)
tiersWboundaries.head()

,msoa_code,easting,northing,intensity,cluster_label,membership_prob,tier,final_weight,msoa21nm,geometry
0,E02000001,532290.3638,181745.9359,95897.337353,228,1.0,Tier 1,95897.337353,City of London 001,"MULTIPOLYGON (((532946.065 181894.827, 532135...."
1,E02000002,547988.0185,189412.9491,9689.155164,-1,0.0,Tier 3,484.457758,Barking and Dagenham 001,"MULTIPOLYGON (((549000.726 190873.464, 548877...."
2,E02000003,548362.0317,188088.2498,15795.621326,-1,0.0,Tier 2,7897.810663,Barking and Dagenham 002,"MULTIPOLYGON (((548954.517 189063.241, 549120...."
3,E02000004,551020.1697,186865.3459,5584.097231,-1,0.0,Tier 3,279.204862,Barking and Dagenham 003,"MULTIPOLYGON (((551943.781 186027.614, 551391...."
4,E02000005,548629.9425,186875.2643,9930.507955,-1,0.0,Tier 3,496.525398,Barking and Dagenham 004,"MULTIPOLYGON (((549418.68 187442.412, 549099.6..."

change the tiers

In [93]:
tier1 = tiersWboundaries[tiersWboundaries["tier"] == "Tier 1"][["msoa_code", "geometry"]].copy()
tier3 = tiersWboundaries[tiersWboundaries["tier"] == "Tier 3"][["msoa_code", "geometry"]].copy()

neighbours = gpd.sjoin(
    tier3,
    tier1,
    how="inner",
    predicate="touches"
)
print(neighbours.head())
neighbour_codes = neighbours["msoa_code_left"].unique()

tiersWboundaries["tier_adjusted"] = tiersWboundaries["tier"]

tiersWboundaries.loc[
   (tiersWboundaries["msoa_code"].isin(neighbour_codes)) &
   (tiersWboundaries["tier_adjusted"] == "Tier 3"),
   "tier_adjusted"
] = "Tier 2"
tiersWboundaries.head()

  msoa_code_left                                           geometry  \
1      E02000002  MULTIPOLYGON (((549000.726 190873.464, 548877....
1      E02000002  MULTIPOLYGON (((549000.726 190873.464, 548877....
1      E02000002  MULTIPOLYGON (((549000.726 190873.464, 548877....
4      E02000005  MULTIPOLYGON (((549418.68 187442.412, 549099.6...
4      E02000005  MULTIPOLYGON (((549418.68 187442.412, 549099.6...

   index_right msoa_code_right
1         6758       E02007017
1          723       E02000763
1          713       E02000752
4            6       E02000008
4         6547       E02006799

,msoa_code,easting,northing,intensity,cluster_label,membership_prob,tier,final_weight,msoa21nm,geometry,tier_adjusted
0,E02000001,532290.3638,181745.9359,95897.337353,228,1.0,Tier 1,95897.337353,City of London 001,"MULTIPOLYGON (((532946.065 181894.827, 532135....",Tier 1
1,E02000002,547988.0185,189412.9491,9689.155164,-1,0.0,Tier 3,484.457758,Barking and Dagenham 001,"MULTIPOLYGON (((549000.726 190873.464, 548877....",Tier 2
2,E02000003,548362.0317,188088.2498,15795.621326,-1,0.0,Tier 2,7897.810663,Barking and Dagenham 002,"MULTIPOLYGON (((548954.517 189063.241, 549120....",Tier 2
3,E02000004,551020.1697,186865.3459,5584.097231,-1,0.0,Tier 3,279.204862,Barking and Dagenham 003,"MULTIPOLYGON (((551943.781 186027.614, 551391....",Tier 3
4,E02000005,548629.9425,186875.2643,9930.507955,-1,0.0,Tier 3,496.525398,Barking and Dagenham 004,"MULTIPOLYGON (((549418.68 187442.412, 549099.6...",Tier 2

how many got changed

In [95]:
changed = tiersWboundaries[
    tiersWboundaries["tier"] != tiersWboundaries["tier_adjusted"]
]

print(len(changed))
print(changed[["msoa_code", "tier", "tier_adjusted"]])

1818
      msoa_code    tier tier_adjusted
1     E02000002  Tier 3        Tier 2
4     E02000005  Tier 3        Tier 2
8     E02000010  Tier 3        Tier 2
11    E02000013  Tier 3        Tier 2
22    E02000024  Tier 3        Tier 2
...         ...     ...           ...
7237  W02000400  Tier 3        Tier 2
7241  W02000404  Tier 3        Tier 2
7250  W02000414  Tier 3        Tier 2
7259  W02000424  Tier 3        Tier 2
7260  W02000425  Tier 3        Tier 2

[1818 rows x 3 columns]

## 5. Print results

In [96]:
print("MSOAs:", len(tiersWboundaries))
print("Clusters found:", tiersWboundaries.loc[tiersWboundaries["cluster_label"] != -1, "cluster_label"].nunique())
print("Noise points:", (tiersWboundaries["cluster_label"] == -1).sum())
print("\nTier counts:")
print(tiersWboundaries["tier_adjusted"].value_counts())

MSOAs: 7264
Clusters found: 313
Noise points: 3406

Tier counts:
tier_adjusted
Tier 1    3566
Tier 2    2955
Tier 3     743
Name: count, dtype: int64

## 6. Save results in /data/processed

In [ ]:
DATA_DIR.mkdir(parents=True, exist_ok=True)
out_path = DATA_DIR / f"tier_assignments_{MONTH}.csv"
result.to_csv(out_path, index=False)
print("Wrote", out_path)