# Cluster & tier assignments

Runs `src.clustering.assign_tiers` on the forecast + PWC data to produce per-MSOA cluster labels and tiers for a chosen month.

**Inputs**
 `data/raw/centroids/msoa_2021_PWCs.csv` population-weighted centroids.
 `data/processed/wide_forecasts.csv` the `wide_forecasts` table built in `regression test.ipynb`.
  It carries `msoa_code`, `month`, and `intensity` columns, which is what `assign_tiers` needs.

Run Jupyter from the repo root so `import src` resolves.

In [14]:
import os
from pathlib import Path

# from dev manual: be at root so 'from src...' resolves.
if not Path("src").is_dir():
    os.chdir(Path.cwd().parent)

import pandas as pd

from src.config import DATA_DIR, RAW_DIR
from src.clustering import assign_tiers, load_pwc_coords

## 1. PWC coordinates
Raw columns `X, Y, MSOA21CD` renamed to `easting, northing, msoa_code`.

In [15]:
pwc = load_pwc_coords(pd.read_csv(RAW_DIR / "centroids" / "msoa_2021_PWCs.csv"))
pwc.head()

   msoa_code      easting     northing
0  E02000001  532290.3638  181745.9359
1  E02004372  582475.5406  110963.8205
2  E02006584  524353.1856  135416.2588
3  E02006411  504326.1721  170345.3420
4  E02003401  470327.0410  172513.7070

Prerequisite

In [16]:
# PREREQUISITE 
# do NOT run this cell here. It is commented out on purpose.                                    
                                                                                                      
# The next section reads data/processed/wide_forecasts.csv. That file is NOT                                
# in git (data/processed/ is gitignored), so it must be generated once from                                  
# the regression notebook before this notebook can run.                                             
                                                                                                            
# HOW TO GENERATE IT:                                                                                          
#   1. Open regression test.ipynb and run it top to bottom so the                                            
#      wide_forecasts DataFrame exists in that kernel's memory.                                              
#   2. With wide_forecasts still in memory, add a new cell at the bottom of                                  
#      regression test.ipynb containing exactly the code below, and run it.                                  
#   3. It writes the CSV to data/processed/. After that, this notebook can read                                
#      it and you do not need to rerun regression again unless forecasts change. 
#   4. after wide_forecasts.csv is saved, delete the code to avoid bloating the other notebook with non regression related code
                                                                                                             
#  Paste the following into regression test.ipynb, NOT into this notebook:                            
#                                                                                                              
# from src.config import DATA_DIR                                                                              
# DATA_DIR.mkdir(parents=True, exist_ok=True)                                                                  
# wide_forecasts.to_csv(DATA_DIR / "wide_forecasts.csv", index=False)

## 2. Forecasts
`instensityforecast12m` already contains `msoa_code`, `month`, `intensity`. `assign_tiers` slices the columns it needs

In [17]:
from sqlalchemy import create_engine 
import pandas as pd
engine = create_engine("postgresql+psycopg2://data_admin:TUE123@localhost:5433/cbl_policing")
wide_forecasts = pd.read_sql("""SELECT *
                             FROM instensityforecast12m
""",engine
    
)

wide_forecasts = wide_forecasts.rename(columns={"msoa_id":"msoa_code"})
wide_forecasts[["msoa_code", "month", "intensity"]].head()

   msoa_code      month      intensity
0  E02000001 2026-04-01  100479.373307
1  E02000002 2026-04-01   10325.070749
2  E02000003 2026-04-01   15712.862295
3  E02000004 2026-04-01    6131.933289
4  E02000005 2026-04-01   10851.012952

## 3. Pick a month
`assign_tiers` clusters one month at a time. Output available months:

In [18]:
months = sorted(wide_forecasts["month"].dt.strftime("%Y-%m-%d").unique())

In [27]:
months_threshold = {}
for MONTH in months:
    # Intensity cutoff for at-risk (TIER 2) noise points, taken from the specific month's distribution.
    month_intensity = wide_forecasts.loc[wide_forecasts["month"] == MONTH, "intensity"]
    threshold_value = 0.3
    THRESHOLD = month_intensity.quantile(threshold_value)
    months_threshold[MONTH] = THRESHOLD
    print(f"Threshold ({threshold_value}th pct of intensity for {MONTH}): {THRESHOLD:.3f}")

Threshold (0.3th pct of intensity for 2026-04-01): 4600.586
Threshold (0.3th pct of intensity for 2026-05-01): 4795.658
Threshold (0.3th pct of intensity for 2026-06-01): 4967.397
Threshold (0.3th pct of intensity for 2026-07-01): 5101.299
Threshold (0.3th pct of intensity for 2026-08-01): 5121.111
Threshold (0.3th pct of intensity for 2026-09-01): 5092.581
Threshold (0.3th pct of intensity for 2026-10-01): 5003.087
Threshold (0.3th pct of intensity for 2026-11-01): 4851.565
Threshold (0.3th pct of intensity for 2026-12-01): 4737.548
Threshold (0.3th pct of intensity for 2027-01-01): 4649.768
Threshold (0.3th pct of intensity for 2027-02-01): 4613.935
Threshold (0.3th pct of intensity for 2027-03-01): 4715.265

## 4. Cluster & assign tiers

In [28]:
results = {}
for MONTH in months_threshold:
    result = assign_tiers(
    wide_forecasts,
    pwc,
    month=MONTH,
    threshold=months_threshold[MONTH],
    intensity_cap_quantile=0.95,
    min_cluster_size=5,
    hotspot_cluster_quantile=0.80,
    )
    results[MONTH] = result
results

{'2026-04-01':       msoa_code      easting     northing      intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  100479.373307            195
 1     E02000002  547988.0185  189412.9491   10325.070749             -1
 2     E02000003  548362.0317  188088.2498   15712.862295             -1
 3     E02000004  551020.1697  186865.3459    6131.933289             -1
 4     E02000005  548629.9425  186875.2643   10851.012952             -1
 ...         ...          ...          ...            ...            ...
 7259  W02000424  335163.1075  354995.9965    3098.377735             -1
 7260  W02000425  337676.4709  353314.4117    6219.017719            169
 7261  W02000426  334519.0819  351685.8545    6082.159973            169
 7262  W02000427  282427.8779  199774.1260    8593.586155             71
 7263  W02000428  259896.7385  193369.4262    3761.342542             76

       membership_prob    tier   final_weight
 0            1.000000  Tier 1  100479.373307
 1            0.000000  Tier 2    5162.535375
 2            0.000000  Tier 2    7856.431148
 3            0.000000  Tier 2    3065.966645
 4            0.000000  Tier 2    5425.506476
 ...               ...     ...            ...
 7259         0.000000  Tier 3     154.918887
 7260         1.000000  Tier 2    3109.508859
 7261         1.000000  Tier 2    3041.079987
 7262         0.956006  Tier 2    4296.793078
 7263         1.000000  Tier 3     188.067127

 [7264 rows x 8 columns],
 '2026-05-01':       msoa_code      easting     northing      intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  101597.704981            235
 1     E02000002  547988.0185  189412.9491   10661.600351             -1
 2     E02000003  548362.0317  188088.2498   15547.424688             -1
 3     E02000004  551020.1697  186865.3459    6367.715669            257
 4     E02000005  548629.9425  186875.2643   10841.274942            258
 ...         ...          ...          ...            ...            ...
 7259  W02000424  335163.1075  354995.9965    3124.579095             -1
 7260  W02000425  337676.4709  353314.4117    6279.416990            148
 7261  W02000426  334519.0819  351685.8545    6434.247813            148
 7262  W02000427  282427.8779  199774.1260    8789.587298             87
 7263  W02000428  259896.7385  193369.4262    3737.458126             90

       membership_prob    tier   final_weight
 0            1.000000  Tier 1  101597.704981
 1            0.000000  Tier 2    5330.800175
 2            0.000000  Tier 2    7773.712344
 3            0.994481  Tier 2    3183.857834
 4            0.961366  Tier 2    5420.637471
 ...               ...     ...            ...
 7259         0.000000  Tier 3     156.228955
 7260         1.000000  Tier 2    3139.708495
 7261         1.000000  Tier 2    3217.123906
 7262         0.894978  Tier 2    4394.793649
 7263         1.000000  Tier 3     186.872906

 [7264 rows x 8 columns],
 '2026-06-01':       msoa_code      easting     northing      intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  102482.876152            247
 1     E02000002  547988.0185  189412.9491   10767.824019            265
 2     E02000003  548362.0317  188088.2498   15261.816416             -1
 3     E02000004  551020.1697  186865.3459    6454.692975            265
 4     E02000005  548629.9425  186875.2643   11451.854915            265
 ...         ...          ...          ...            ...            ...
 7259  W02000424  335163.1075  354995.9965    3436.387681             -1
 7260  W02000425  337676.4709  353314.4117    6755.772086            136
 7261  W02000426  334519.0819  351685.8545    6723.069388            136
 7262  W02000427  282427.8779  199774.1260    8983.732996             -1
 7263  W02000428  259896.7385  193369.4262    3996.207435            103

       membership_prob    tier   final_weight
 0            1.000000  Tier 1  102482.876152
 1            1.000000  Tier 2    5383.912009
 2            0.000000  Tier 2    7630.908208
 3            1.000000  Tier 2    3227.346487
 4            1.000000  Tier 2    5725.927458
 ...               ...     ...            ...
 7259         0.000000  Tier 3     171.819384
 7260         1.000000  Tier 2    3377.886043
 7261         1.000000  Tier 2    3361.534694
 7262         0.000000  Tier 2    4491.866498
 7263         0.928016  Tier 3     199.810372

 [7264 rows x 8 columns],
 '2026-07-01':       msoa_code      easting     northing      intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  100638.904182            163
 1     E02000002  547988.0185  189412.9491   10916.887428            260
 2     E02000003  548362.0317  188088.2498   15555.113935             -1
 3     E02000004  551020.1697  186865.3459    6496.930773            260
 4     E02000005  548629.9425  186875.2643   11261.668727            260
 ...         ...          ...          ...            ...            ...
 7259  W02000424  335163.1075  354995.9965    3652.972720             -1
 7260  W02000425  337676.4709  353314.4117    6927.328615            132
 7261  W02000426  334519.0819  351685.8545    6596.931175            132
 7262  W02000427  282427.8779  199774.1260    8930.504225             -1
 7263  W02000428  259896.7385  193369.4262    4054.133201            122

       membership_prob    tier   final_weight
 0                 1.0  Tier 1  100638.904182
 1                 1.0  Tier 2    5458.443714
 2                 0.0  Tier 2    7777.556967
 3                 1.0  Tier 2    3248.465386
 4                 1.0  Tier 2    5630.834364
 ...               ...     ...            ...
 7259              0.0  Tier 3     182.648636
 7260              1.0  Tier 2    3463.664307
 7261              1.0  Tier 2    3298.465587
 7262              0.0  Tier 2    4465.252113
 7263              1.0  Tier 3     202.706660

 [7264 rows x 8 columns],
 '2026-08-01':       msoa_code      easting     northing     intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  99967.637026            226
 1     E02000002  547988.0185  189412.9491  11068.935650            264
 2     E02000003  548362.0317  188088.2498  15159.372916             -1
 3     E02000004  551020.1697  186865.3459   6619.346594             -1
 4     E02000005  548629.9425  186875.2643  10987.232659            264
 ...         ...          ...          ...           ...            ...
 7259  W02000424  335163.1075  354995.9965   3635.823481             -1
 7260  W02000425  337676.4709  353314.4117   6970.980583            141
 7261  W02000426  334519.0819  351685.8545   6756.114420            141
 7262  W02000427  282427.8779  199774.1260   9025.214678             -1
 7263  W02000428  259896.7385  193369.4262   4230.696461            105

       membership_prob    tier  final_weight
 0            1.000000  Tier 1  99967.637026
 1            0.637638  Tier 2   5534.467825
 2            0.000000  Tier 2   7579.686458
 3            0.000000  Tier 2   3309.673297
 4            0.771443  Tier 2   5493.616329
 ...               ...     ...           ...
 7259         0.000000  Tier 3    181.791174
 7260         1.000000  Tier 2   3485.490292
 7261         1.000000  Tier 2   3378.057210
 7262         0.000000  Tier 2   4512.607339
 7263         1.000000  Tier 3    211.534823

 [7264 rows x 8 columns],
 '2026-09-01':       msoa_code      easting     northing     intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  99182.002324            192
 1     E02000002  547988.0185  189412.9491  10964.331781            299
 2     E02000003  548362.0317  188088.2498  14865.008605             -1
 3     E02000004  551020.1697  186865.3459   6494.510235             -1
 4     E02000005  548629.9425  186875.2643  11330.377373            299
 ...         ...          ...          ...           ...            ...
 7259  W02000424  335163.1075  354995.9965   3662.189628             -1
 7260  W02000425  337676.4709  353314.4117   6880.532755            143
 7261  W02000426  334519.0819  351685.8545   6766.136026            143
 7262  W02000427  282427.8779  199774.1260   8674.866161             82
 7263  W02000428  259896.7385  193369.4262   4135.036152             85

       membership_prob    tier  final_weight
 0            1.000000  Tier 1  99182.002324
 1            1.000000  Tier 2   5482.165890
 2            0.000000  Tier 2   7432.504302
 3            0.000000  Tier 2   3247.255118
 4            1.000000  Tier 2   5665.188687
 ...               ...     ...           ...
 7259         0.000000  Tier 3    183.109481
 7260         1.000000  Tier 2   3440.266377
 7261         1.000000  Tier 2   3383.068013
 7262         0.757594  Tier 2   4337.433080
 7263         0.954224  Tier 3    206.751808

 [7264 rows x 8 columns],
 '2026-10-01':       msoa_code      easting     northing     intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  99760.271960             63
 1     E02000002  547988.0185  189412.9491  10413.969617             -1
 2     E02000003  548362.0317  188088.2498  15113.850392             -1
 3     E02000004  551020.1697  186865.3459   6407.747450             -1
 4     E02000005  548629.9425  186875.2643  11502.073192             -1
 ...         ...          ...          ...           ...            ...
 7259  W02000424  335163.1075  354995.9965   3562.543495             -1
 7260  W02000425  337676.4709  353314.4117   6582.765997            156
 7261  W02000426  334519.0819  351685.8545   6442.376792            156
 7262  W02000427  282427.8779  199774.1260   8925.746503             -1
 7263  W02000428  259896.7385  193369.4262   4006.280821             96

       membership_prob    tier  final_weight
 0                 1.0  Tier 1  99760.271960
 1                 0.0  Tier 2   5206.984808
 2                 0.0  Tier 2   7556.925196
 3                 0.0  Tier 2   3203.873725
 4                 0.0  Tier 2   5751.036596
 ...               ...     ...           ...
 7259              0.0  Tier 3    178.127175
 7260              1.0  Tier 2   3291.382998
 7261              1.0  Tier 2   3221.188396
 7262              0.0  Tier 2   4462.873252
 7263              1.0  Tier 3    200.314041

 [7264 rows x 8 columns],
 '2026-11-01':       msoa_code      easting     northing     intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  98629.225612            226
 1     E02000002  547988.0185  189412.9491  10901.079842            287
 2     E02000003  548362.0317  188088.2498  15437.362135             -1
 3     E02000004  551020.1697  186865.3459   6300.041339             -1
 4     E02000005  548629.9425  186875.2643  11043.421193             -1
 ...         ...          ...          ...           ...            ...
 7259  W02000424  335163.1075  354995.9965   3346.055914             -1
 7260  W02000425  337676.4709  353314.4117   6526.171510            172
 7261  W02000426  334519.0819  351685.8545   6467.212880            172
 7262  W02000427  282427.8779  199774.1260   8858.148523             -1
 7263  W02000428  259896.7385  193369.4262   3853.258590            100

       membership_prob    tier  final_weight
 0            1.000000  Tier 1  98629.225612
 1            0.971868  Tier 2   5450.539921
 2            0.000000  Tier 2   7718.681068
 3            0.000000  Tier 2   3150.020669
 4            0.000000  Tier 2   5521.710597
 ...               ...     ...           ...
 7259         0.000000  Tier 3    167.302796
 7260         1.000000  Tier 2   3263.085755
 7261         1.000000  Tier 2   3233.606440
 7262         0.000000  Tier 2   4429.074262
 7263         1.000000  Tier 3    192.662929

 [7264 rows x 8 columns],
 '2026-12-01':       msoa_code      easting     northing      intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  100748.733984            161
 1     E02000002  547988.0185  189412.9491   10405.607374             -1
 2     E02000003  548362.0317  188088.2498   14989.269647             -1
 3     E02000004  551020.1697  186865.3459    6106.215481            277
 4     E02000005  548629.9425  186875.2643   11059.448104            273
 ...         ...          ...          ...            ...            ...
 7259  W02000424  335163.1075  354995.9965    3277.210064             -1
 7260  W02000425  337676.4709  353314.4117    6395.989001            100
 7261  W02000426  334519.0819  351685.8545    6433.980224            100
 7262  W02000427  282427.8779  199774.1260    8701.545698             -1
 7263  W02000428  259896.7385  193369.4262    3681.807690             90

       membership_prob    tier   final_weight
 0            1.000000  Tier 1  100748.733984
 1            0.000000  Tier 2    5202.803687
 2            0.000000  Tier 2    7494.634824
 3            0.960774  Tier 2    3053.107741
 4            0.976531  Tier 2    5529.724052
 ...               ...     ...            ...
 7259         0.000000  Tier 3     163.860503
 7260         1.000000  Tier 2    3197.994500
 7261         1.000000  Tier 2    3216.990112
 7262         0.000000  Tier 2    4350.772849
 7263         1.000000  Tier 3     184.090384

 [7264 rows x 8 columns],
 '2027-01-01':       msoa_code      easting     northing     intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  98633.484507            120
 1     E02000002  547988.0185  189412.9491  10439.128187            256
 2     E02000003  548362.0317  188088.2498  14793.088199             -1
 3     E02000004  551020.1697  186865.3459   5989.637636            256
 4     E02000005  548629.9425  186875.2643  10991.222852            256
 ...         ...          ...          ...           ...            ...
 7259  W02000424  335163.1075  354995.9965   3157.514045             -1
 7260  W02000425  337676.4709  353314.4117   6140.771405            169
 7261  W02000426  334519.0819  351685.8545   6196.389268            169
 7262  W02000427  282427.8779  199774.1260   8605.630887             -1
 7263  W02000428  259896.7385  193369.4262   3592.113955            113

       membership_prob    tier  final_weight
 0                 1.0  Tier 1  98633.484507
 1                 1.0  Tier 2   5219.564094
 2                 0.0  Tier 2   7396.544099
 3                 1.0  Tier 2   2994.818818
 4                 1.0  Tier 2   5495.611426
 ...               ...     ...           ...
 7259              0.0  Tier 3    157.875702
 7260              1.0  Tier 2   3070.385703
 7261              1.0  Tier 2   3098.194634
 7262              0.0  Tier 2   4302.815444
 7263              1.0  Tier 3    179.605698

 [7264 rows x 8 columns],
 '2027-02-01':       msoa_code      easting     northing     intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  97094.037404            176
 1     E02000002  547988.0185  189412.9491  10355.697549            269
 2     E02000003  548362.0317  188088.2498  14571.081631             -1
 3     E02000004  551020.1697  186865.3459   6135.331882            262
 4     E02000005  548629.9425  186875.2643  10759.353149            269
 ...         ...          ...          ...           ...            ...
 7259  W02000424  335163.1075  354995.9965   3072.449515             -1
 7260  W02000425  337676.4709  353314.4117   6368.161055            127
 7261  W02000426  334519.0819  351685.8545   6133.169001            127
 7262  W02000427  282427.8779  199774.1260   8314.809153             91
 7263  W02000428  259896.7385  193369.4262   3627.191368             96

       membership_prob    tier  final_weight
 0            1.000000  Tier 1  97094.037404
 1            0.862626  Tier 2   5177.848775
 2            0.000000  Tier 2   7285.540815
 3            0.994393  Tier 2   3067.665941
 4            1.000000  Tier 2   5379.676574
 ...               ...     ...           ...
 7259         0.000000  Tier 3    153.622476
 7260         1.000000  Tier 2   3184.080528
 7261         1.000000  Tier 2   3066.584500
 7262         0.913587  Tier 2   4157.404576
 7263         1.000000  Tier 3    181.359568

 [7264 rows x 8 columns],
 '2027-03-01':       msoa_code      easting     northing     intensity  cluster_label  \
 0     E02000001  532290.3638  181745.9359  96902.346793             46
 1     E02000002  547988.0185  189412.9491  10347.893887            277
 2     E02000003  548362.0317  188088.2498  14677.489137             -1
 3     E02000004  551020.1697  186865.3459   6133.851178             -1
 4     E02000005  548629.9425  186875.2643  10724.873696            277
 ...         ...          ...          ...           ...            ...
 7259  W02000424  335163.1075  354995.9965   3294.538329             -1
 7260  W02000425  337676.4709  353314.4117   6326.531459            143
 7261  W02000426  334519.0819  351685.8545   6296.938849            143
 7262  W02000427  282427.8779  199774.1260   8478.723457             -1
 7263  W02000428  259896.7385  193369.4262   3815.519891            100

       membership_prob    tier  final_weight
 0            1.000000  Tier 1  96902.346793
 1            0.901907  Tier 2   5173.946943
 2            0.000000  Tier 2   7338.744569
 3            0.000000  Tier 2   3066.925589
 4            1.000000  Tier 2   5362.436848
 ...               ...     ...           ...
 7259         0.000000  Tier 3    164.726916
 7260         1.000000  Tier 2   3163.265730
 7261         1.000000  Tier 2   3148.469425
 7262         0.000000  Tier 2   4239.361729
 7263         0.992698  Tier 3    190.775995

 [7264 rows x 8 columns]}

## 5. change tiers of t1 neighbours

In [29]:
import geopandas as gpd

boundaries = gpd.read_file("data/raw/boundaries/msoa_2021_Boundaries_BSC.gpkg")
boundaries = boundaries[["MSOA21CD","MSOA21NM","geometry"]]
boundaries = boundaries.rename(columns={

    "MSOA21CD": "msoa_code",

    "MSOA21NM": "msoa21nm"

})
boundaries.head()

,msoa_code,msoa21nm,geometry
0,E02000001,City of London 001,"MULTIPOLYGON (((532946.065 181894.827, 532135...."
1,E02000002,Barking and Dagenham 001,"MULTIPOLYGON (((549000.726 190873.464, 548877...."
2,E02000003,Barking and Dagenham 002,"MULTIPOLYGON (((548954.517 189063.241, 549120...."
3,E02000004,Barking and Dagenham 003,"MULTIPOLYGON (((551943.781 186027.614, 551391...."
4,E02000005,Barking and Dagenham 004,"MULTIPOLYGON (((549418.68 187442.412, 549099.6..."

In [30]:
tiersWboundariesALL = {}
for month, prediction in results.items():
    tiersWboundariesALL[month] = results[month].merge(boundaries,on= "msoa_code",how="left")
    tiersWboundariesALL[month] = gpd.GeoDataFrame(tiersWboundariesALL[month],geometry="geometry",crs=boundaries.crs)

change the tiers

In [31]:
for month,_ in tiersWboundariesALL.items():
    tier1 = tiersWboundariesALL[month][tiersWboundariesALL[month]["tier"] == "Tier 1"][["msoa_code", "geometry"]].copy()
    tier3 = tiersWboundariesALL[month][tiersWboundariesALL[month]["tier"] == "Tier 3"][["msoa_code", "geometry"]].copy()

    neighbours = gpd.sjoin(
        tier3,
        tier1,
        how="inner",
        predicate="touches"
    )
    #print(neighbours.head())
    neighbour_codes = neighbours["msoa_code_left"].unique()

    tiersWboundariesALL[month]["tier_adjusted"] = tiersWboundariesALL[month]["tier"]
    #print(tiersWboundariesALL[month])
    tiersWboundariesALL[month].loc[
    (tiersWboundariesALL[month]["msoa_code"].isin(neighbour_codes)) &
    (tiersWboundariesALL[month]["tier_adjusted"] == "Tier 3"),
    "tier_adjusted"
    ] = "Tier 2"
    print(tiersWboundariesALL["2026-04-01"])

      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1
1     MULTIPOLYGON (((549000.726 190873.464, 548877....        Tier 2
2     MULTIPOLYGON (((548954.517 189063.241, 549120....        Tier 2
3     MULTIPOLYGON (((551943.781 186027.614, 551391....        Tier 2
4     MULTIPOLYGON (((549418.68 187442.412, 549099.6...        Tier 2
...                                                 ...           ...
7259  MULTIPOLYGON (((334882.839 352624.88, 335805.0...        Tier 3
7260  MULTIPOLYGON (((335607.436 359944.375, 335031....        Tier 2
7261  MULTIPOLYGON (((334882.839 352624.88, 334312.8...        Tier 2
7262  MULTIPOLYGON (((290787 202886.298, 289563.094 ...        Tier 2
7263  MULTIPOLYGON (((261080.594 194576.702, 260436....        Tier 3

[7264 rows x 11 columns]
      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1
1     MULTIPOLYGON (((549000.726 190873.464, 548877....        Tier 2
2     MULTIPOLYGON (((548954.517 189063.241, 549120....        Tier 2
3     MULTIPOLYGON (((551943.781 186027.614, 551391....        Tier 2
4     MULTIPOLYGON (((549418.68 187442.412, 549099.6...        Tier 2
...                                                 ...           ...
7259  MULTIPOLYGON (((334882.839 352624.88, 335805.0...        Tier 3
7260  MULTIPOLYGON (((335607.436 359944.375, 335031....        Tier 2
7261  MULTIPOLYGON (((334882.839 352624.88, 334312.8...        Tier 2
7262  MULTIPOLYGON (((290787 202886.298, 289563.094 ...        Tier 2
7263  MULTIPOLYGON (((261080.594 194576.702, 260436....        Tier 3

[7264 rows x 11 columns]
      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1
1     MULTIPOLYGON (((549000.726 190873.464, 548877....        Tier 2
2     MULTIPOLYGON (((548954.517 189063.241, 549120....        Tier 2
3     MULTIPOLYGON (((551943.781 186027.614, 551391....        Tier 2
4     MULTIPOLYGON (((549418.68 187442.412, 549099.6...        Tier 2
...                                                 ...           ...
7259  MULTIPOLYGON (((334882.839 352624.88, 335805.0...        Tier 3
7260  MULTIPOLYGON (((335607.436 359944.375, 335031....        Tier 2
7261  MULTIPOLYGON (((334882.839 352624.88, 334312.8...        Tier 2
7262  MULTIPOLYGON (((290787 202886.298, 289563.094 ...        Tier 2
7263  MULTIPOLYGON (((261080.594 194576.702, 260436....        Tier 3

[7264 rows x 11 columns]
      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1
1     MULTIPOLYGON (((549000.726 190873.464, 548877....        Tier 2
2     MULTIPOLYGON (((548954.517 189063.241, 549120....        Tier 2
3     MULTIPOLYGON (((551943.781 186027.614, 551391....        Tier 2
4     MULTIPOLYGON (((549418.68 187442.412, 549099.6...        Tier 2
...                                                 ...           ...
7259  MULTIPOLYGON (((334882.839 352624.88, 335805.0...        Tier 3
7260  MULTIPOLYGON (((335607.436 359944.375, 335031....        Tier 2
7261  MULTIPOLYGON (((334882.839 352624.88, 334312.8...        Tier 2
7262  MULTIPOLYGON (((290787 202886.298, 289563.094 ...        Tier 2
7263  MULTIPOLYGON (((261080.594 194576.702, 260436....        Tier 3

[7264 rows x 11 columns]
      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1
1     MULTIPOLYGON (((549000.726 190873.464, 548877....        Tier 2
2     MULTIPOLYGON (((548954.517 189063.241, 549120....        Tier 2
3     MULTIPOLYGON (((551943.781 186027.614, 551391....        Tier 2
4     MULTIPOLYGON (((549418.68 187442.412, 549099.6...        Tier 2
...                                                 ...           ...
7259  MULTIPOLYGON (((334882.839 352624.88, 335805.0...        Tier 3
7260  MULTIPOLYGON (((335607.436 359944.375, 335031....        Tier 2
7261  MULTIPOLYGON (((334882.839 352624.88, 334312.8...        Tier 2
7262  MULTIPOLYGON (((290787 202886.298, 289563.094 ...        Tier 2
7263  MULTIPOLYGON (((261080.594 194576.702, 260436....        Tier 3

[7264 rows x 11 columns]
      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1
1     MULTIPOLYGON (((549000.726 190873.464, 548877....        Tier 2
2     MULTIPOLYGON (((548954.517 189063.241, 549120....        Tier 2
3     MULTIPOLYGON (((551943.781 186027.614, 551391....        Tier 2
4     MULTIPOLYGON (((549418.68 187442.412, 549099.6...        Tier 2
...                                                 ...           ...
7259  MULTIPOLYGON (((334882.839 352624.88, 335805.0...        Tier 3
7260  MULTIPOLYGON (((335607.436 359944.375, 335031....        Tier 2
7261  MULTIPOLYGON (((334882.839 352624.88, 334312.8...        Tier 2
7262  MULTIPOLYGON (((290787 202886.298, 289563.094 ...        Tier 2
7263  MULTIPOLYGON (((261080.594 194576.702, 260436....        Tier 3

[7264 rows x 11 columns]
      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1
1     MULTIPOLYGON (((549000.726 190873.464, 548877....        Tier 2
2     MULTIPOLYGON (((548954.517 189063.241, 549120....        Tier 2
3     MULTIPOLYGON (((551943.781 186027.614, 551391....        Tier 2
4     MULTIPOLYGON (((549418.68 187442.412, 549099.6...        Tier 2
...                                                 ...           ...
7259  MULTIPOLYGON (((334882.839 352624.88, 335805.0...        Tier 3
7260  MULTIPOLYGON (((335607.436 359944.375, 335031....        Tier 2
7261  MULTIPOLYGON (((334882.839 352624.88, 334312.8...        Tier 2
7262  MULTIPOLYGON (((290787 202886.298, 289563.094 ...        Tier 2
7263  MULTIPOLYGON (((261080.594 194576.702, 260436....        Tier 3

[7264 rows x 11 columns]
      msoa_code      easting     northing      intensity  cluster_label  \
0     E02000001  532290.3638  181745.9359  100479.373307            195
1     E02000002  547988.0185  189412.9491   10325.070749             -1
2     E02000003  548362.0317  188088.2498   15712.862295             -1
3     E02000004  551020.1697  186865.3459    6131.933289             -1
4     E02000005  548629.9425  186875.2643   10851.012952             -1
...         ...          ...          ...            ...            ...
7259  W02000424  335163.1075  354995.9965    3098.377735             -1
7260  W02000425  337676.4709  353314.4117    6219.017719            169
7261  W02000426  334519.0819  351685.8545    6082.159973            169
7262  W02000427  282427.8779  199774.1260    8593.586155             71
7263  W02000428  259896.7385  193369.4262    3761.342542             76

      membership_prob    tier   final_weight                  msoa21nm  \
0            1.000000  Tier 1  100479.373307        City of London 001
1            0.000000  Tier 2    5162.535375  Barking and Dagenham 001
2            0.000000  Tier 2    7856.431148  Barking and Dagenham 002
3            0.000000  Tier 2    3065.966645  Barking and Dagenham 003
4            0.000000  Tier 2    5425.506476  Barking and Dagenham 004
...               ...     ...            ...                       ...
7259         0.000000  Tier 3     154.918887               Wrexham 021
7260         1.000000  Tier 2    3109.508859               Wrexham 022
7261         1.000000  Tier 2    3041.079987               Wrexham 023
7262         0.956006  Tier 2    4296.793078     Neath Port Talbot 021
7263         1.000000  Tier 3     188.067127               Swansea 032

                                               geometry tier_adjusted
0     MULTIPOLYGON (((532946.065 181894.827, 532135....        Tier 1

how many got changed

In [32]:
changed = {}
for month,_ in tiersWboundariesALL.items():
    changed[month] = tiersWboundariesALL[month][
        tiersWboundariesALL[month]["tier"] != tiersWboundariesALL[month]["tier_adjusted"]
    ]

    print(len(changed[month]))
    #print(changed[month][["msoa_code", "tier", "tier_adjusted"]])

182
152
161
168
159
185
195
198
179
194
171
200

## 5. Print results

In [33]:
result = tiersWboundariesALL["2026-04-01"]
print("MSOAs:", len(result))
print("Clusters found:", result.loc[result["cluster_label"] != -1, "cluster_label"].nunique())
print("Noise points:", (result["cluster_label"] == -1).sum())
print("\nTier counts:")
print(result["tier"].value_counts())

MSOAs: 7264
Clusters found: 306
Noise points: 3322

Tier counts:
tier
Tier 2    4368
Tier 3    2179
Tier 1     717
Name: count, dtype: int64

## 6. Save results in /data/processed

In [34]:
for month,result in tiersWboundariesALL.items():
    result = pd.DataFrame(result.drop(columns="geometry"))
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    out_path = DATA_DIR / 'monthly_tiers' / f"tier_assignments_{month}.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(out_path, index=False)
    print("Wrote", out_path)

Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-04-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-05-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-06-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-07-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-08-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-09-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-10-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-11-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2026-12-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2027-01-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2027-02-01.csv
Wrote C:\Users\admin\Downloads\cbl-project\TUe-Multi-Disciplinary-CBL\data\processed\monthly_tiers\tier_assignments_2027-03-01.csv