# Cluster & tier assignments

Runs `src.clustering.assign_tiers` on the forecast + PWC data to produce per-MSOA cluster labels and tiers for a chosen month.

**Inputs**
 `data/raw/centroids/msoa_2021_PWCs.csv` population-weighted centroids.
 `data/processed/wide_forecasts.csv` the `wide_forecasts` table built in `regression test.ipynb`.
  It carries `msoa_code`, `month`, and `intensity` columns, which is what `assign_tiers` needs.

Run Jupyter from the repo root so `import src` resolves.

In [39]:
import os
from pathlib import Path

# from dev manual: be at root so 'from src...' resolves.
if not Path("src").is_dir():
    os.chdir(Path.cwd().parent)

import pandas as pd

from src.config import DATA_DIR, RAW_DIR
from src.clustering import assign_tiers, load_pwc_coords

## 1. PWC coordinates
Raw columns `X, Y, MSOA21CD` renamed to `easting, northing, msoa_code`.

In [40]:
pwc = load_pwc_coords(pd.read_csv(RAW_DIR / "centroids" / "msoa_2021_PWCs.csv"))
pwc.head()

   msoa_code      easting     northing
0  E02000001  532290.3638  181745.9359
1  E02004372  582475.5406  110963.8205
2  E02006584  524353.1856  135416.2588
3  E02006411  504326.1721  170345.3420
4  E02003401  470327.0410  172513.7070

Prerequisite

In [41]:
# PREREQUISITE 
# do NOT run this cell here. It is commented out on purpose.                                    
                                                                                                      
# The next section reads data/processed/wide_forecasts.csv. That file is NOT                                
# in git (data/processed/ is gitignored), so it must be generated once from                                  
# the regression notebook before this notebook can run.                                             
                                                                                                            
# HOW TO GENERATE IT:                                                                                          
#   1. Open regression test.ipynb and run it top to bottom so the                                            
#      wide_forecasts DataFrame exists in that kernel's memory.                                              
#   2. With wide_forecasts still in memory, add a new cell at the bottom of                                  
#      regression test.ipynb containing exactly the code below, and run it.                                  
#   3. It writes the CSV to data/processed/. After that, this notebook can read                                
#      it and you do not need to rerun regression again unless forecasts change. 
#   4. after wide_forecasts.csv is saved, delete the code to avoid bloating the other notebook with non regression related code
                                                                                                             
#  Paste the following into regression test.ipynb, NOT into this notebook:                            
#                                                                                                              
# from src.config import DATA_DIR                                                                              
# DATA_DIR.mkdir(parents=True, exist_ok=True)                                                                  
# wide_forecasts.to_csv(DATA_DIR / "wide_forecasts.csv", index=False)

## 2. Forecasts
`instensityforecast12m` already contains `msoa_code`, `month`, `intensity`. `assign_tiers` slices the columns it needs

In [42]:
from sqlalchemy import create_engine 
import pandas as pd
engine = create_engine("postgresql+psycopg2://data_admin:TUE123@localhost:5433/cbl_policing")
wide_forecasts = pd.read_sql("""SELECT *
                             FROM instensityforecast12m
""",engine
    
)

wide_forecasts = wide_forecasts.rename(columns={"msoa_id":"msoa_code"})
wide_forecasts[["msoa_code", "month", "intensity"]].head()

   msoa_code      month      intensity
0  E02000001 2026-04-01  100479.373307
1  E02000002 2026-04-01   10325.070749
2  E02000003 2026-04-01   15712.862295
3  E02000004 2026-04-01    6131.933289
4  E02000005 2026-04-01   10851.012952

## 3. Pick a month
`assign_tiers` clusters one month at a time. Output available months:

In [43]:
months = sorted(wide_forecasts["month"].dt.strftime("%Y-%m-%d").unique())

In [44]:
months_threshold = {}
for MONTH in months:
    # Intensity cutoff for at-risk (TIER 2) noise points, taken from the specific month's distribution.
    month_intensity = wide_forecasts.loc[wide_forecasts["month"] == MONTH, "intensity"]
    threshold_value = 0.3
    THRESHOLD = month_intensity.quantile(threshold_value)
    months_threshold[MONTH] = THRESHOLD
    print(f"Threshold ({threshold_value}th pct of intensity for {MONTH}): {THRESHOLD:.3f}")

Threshold (0.3th pct of intensity for 2026-04-01): 4600.586
Threshold (0.3th pct of intensity for 2026-05-01): 4795.658
Threshold (0.3th pct of intensity for 2026-06-01): 4967.397
Threshold (0.3th pct of intensity for 2026-07-01): 5101.299
Threshold (0.3th pct of intensity for 2026-08-01): 5121.111
Threshold (0.3th pct of intensity for 2026-09-01): 5092.581
Threshold (0.3th pct of intensity for 2026-10-01): 5003.087
Threshold (0.3th pct of intensity for 2026-11-01): 4851.565
Threshold (0.3th pct of intensity for 2026-12-01): 4737.548
Threshold (0.3th pct of intensity for 2027-01-01): 4649.768
Threshold (0.3th pct of intensity for 2027-02-01): 4613.935
Threshold (0.3th pct of intensity for 2027-03-01): 4715.265

## 4. Cluster & assign tiers

In [45]:
results = {}
for MONTH in months_threshold:
    result = assign_tiers(
    wide_forecasts,
    pwc,
    month=MONTH,
    threshold=months_threshold[MONTH],
    intensity_cap_quantile=0.95,
    min_cluster_size=5,
    high_confidence_prob=0.9,
    )
    results[MONTH] = result

## 5. change tiers of t1 neighbours

In [46]:
import geopandas as gpd

boundaries = gpd.read_file("data/raw/boundaries/msoa_2021_Boundaries_BSC.gpkg")
boundaries = boundaries[["MSOA21CD","MSOA21NM","geometry"]]
boundaries = boundaries.rename(columns={

    "MSOA21CD": "msoa_code",

    "MSOA21NM": "msoa21nm"

})
boundaries.head()

,msoa_code,msoa21nm,geometry
0,E02000001,City of London 001,"MULTIPOLYGON (((532946.065 181894.827, 532135...."
1,E02000002,Barking and Dagenham 001,"MULTIPOLYGON (((549000.726 190873.464, 548877...."
2,E02000003,Barking and Dagenham 002,"MULTIPOLYGON (((548954.517 189063.241, 549120...."
3,E02000004,Barking and Dagenham 003,"MULTIPOLYGON (((551943.781 186027.614, 551391...."
4,E02000005,Barking and Dagenham 004,"MULTIPOLYGON (((549418.68 187442.412, 549099.6..."

In [47]:
tiersWboundaries = result.merge(boundaries,on= "msoa_code",how="left")
tiersWboundaries = gpd.GeoDataFrame(tiersWboundaries,geometry="geometry",crs=boundaries.crs)
tiersWboundaries.head()

,msoa_code,easting,northing,intensity,cluster_label,membership_prob,tier,final_weight,msoa21nm,geometry
0,E02000001,532290.3638,181745.9359,96902.346793,46,1.000000,Tier 1,96902.346793,City of London 001,"MULTIPOLYGON (((532946.065 181894.827, 532135...."
1,E02000002,547988.0185,189412.9491,10347.893887,278,0.901907,Tier 1,10347.893887,Barking and Dagenham 001,"MULTIPOLYGON (((549000.726 190873.464, 548877...."
2,E02000003,548362.0317,188088.2498,14677.489137,-1,0.000000,Tier 2,7338.744569,Barking and Dagenham 002,"MULTIPOLYGON (((548954.517 189063.241, 549120...."
3,E02000004,551020.1697,186865.3459,6133.851178,-1,0.000000,Tier 2,3066.925589,Barking and Dagenham 003,"MULTIPOLYGON (((551943.781 186027.614, 551391...."
4,E02000005,548629.9425,186875.2643,10724.873696,278,1.000000,Tier 1,10724.873696,Barking and Dagenham 004,"MULTIPOLYGON (((549418.68 187442.412, 549099.6..."

change the tiers

In [48]:
tier1 = tiersWboundaries[tiersWboundaries["tier"] == "Tier 1"][["msoa_code", "geometry"]].copy()
tier3 = tiersWboundaries[tiersWboundaries["tier"] == "Tier 3"][["msoa_code", "geometry"]].copy()

neighbours = gpd.sjoin(
    tier3,
    tier1,
    how="inner",
    predicate="touches"
)
print(neighbours.head())
neighbour_codes = neighbours["msoa_code_left"].unique()

tiersWboundaries["tier_adjusted"] = tiersWboundaries["tier"]

tiersWboundaries.loc[
   (tiersWboundaries["msoa_code"].isin(neighbour_codes)) &
   (tiersWboundaries["tier_adjusted"] == "Tier 3"),
   "tier_adjusted"
] = "Tier 2"
tiersWboundaries.head()

    msoa_code_left                                           geometry  \
24       E02000026  MULTIPOLYGON (((528454.957 195371.311, 527948....
24       E02000026  MULTIPOLYGON (((528454.957 195371.311, 527948....
41       E02000043  MULTIPOLYGON (((525578.293 192368.443, 525190....
41       E02000043  MULTIPOLYGON (((525578.293 192368.443, 525190....
132      E02000138  MULTIPOLYGON (((538643.366 170272.931, 537685....

     index_right msoa_code_right
24            30       E02000032
24           272       E02000287
41            38       E02000040
41            28       E02000030
132         6536       E02006787

,msoa_code,easting,northing,intensity,cluster_label,membership_prob,tier,final_weight,msoa21nm,geometry,tier_adjusted
0,E02000001,532290.3638,181745.9359,96902.346793,46,1.000000,Tier 1,96902.346793,City of London 001,"MULTIPOLYGON (((532946.065 181894.827, 532135....",Tier 1
1,E02000002,547988.0185,189412.9491,10347.893887,278,0.901907,Tier 1,10347.893887,Barking and Dagenham 001,"MULTIPOLYGON (((549000.726 190873.464, 548877....",Tier 1
2,E02000003,548362.0317,188088.2498,14677.489137,-1,0.000000,Tier 2,7338.744569,Barking and Dagenham 002,"MULTIPOLYGON (((548954.517 189063.241, 549120....",Tier 2
3,E02000004,551020.1697,186865.3459,6133.851178,-1,0.000000,Tier 2,3066.925589,Barking and Dagenham 003,"MULTIPOLYGON (((551943.781 186027.614, 551391....",Tier 2
4,E02000005,548629.9425,186875.2643,10724.873696,278,1.000000,Tier 1,10724.873696,Barking and Dagenham 004,"MULTIPOLYGON (((549418.68 187442.412, 549099.6...",Tier 1

how many got changed

In [49]:
changed = tiersWboundaries[
    tiersWboundaries["tier"] != tiersWboundaries["tier_adjusted"]
]

print(len(changed))
print(changed[["msoa_code", "tier", "tier_adjusted"]])

595
      msoa_code    tier tier_adjusted
24    E02000026  Tier 3        Tier 2
41    E02000043  Tier 3        Tier 2
132   E02000138  Tier 3        Tier 2
140   E02000147  Tier 3        Tier 2
154   E02000161  Tier 3        Tier 2
...         ...     ...           ...
7215  W02000378  Tier 3        Tier 2
7222  W02000385  Tier 3        Tier 2
7224  W02000387  Tier 3        Tier 2
7227  W02000390  Tier 3        Tier 2
7259  W02000424  Tier 3        Tier 2

[595 rows x 3 columns]

## 5. Print results

In [52]:
result = tiersWboundaries
print("MSOAs:", len(result))
print("Clusters found:", result.loc[result["cluster_label"] != -1, "cluster_label"].nunique())
print("Noise points:", (result["cluster_label"] == -1).sum())
print("\nTier counts:")
print(result["tier"].value_counts())

MSOAs: 7264
Clusters found: 287
Noise points: 3228

Tier counts:
tier
Tier 2    3312
Tier 1    3070
Tier 3     882
Name: count, dtype: int64

## 6. Save results in /data/processed

In [53]:

DATA_DIR.mkdir(parents=True, exist_ok=True)
out_path = DATA_DIR / f"tier_assignments_{MONTH}.csv"
result.to_csv(out_path, index=False)
print("Wrote", out_path)

Wrote /Users/navi/Documents/UNI/Y2/Q4/CBL/code/TUe-Multi-Disciplinary-CBL/data/processed/tier_assignments_2027-03-01.csv